version: '3.8'
services:
  bot:
    build: .
    container_name: lavamusic_bot
    env_file: .env # Make sure tumhari .env file yahan ho
    depends_on:
      - lavalink

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:3 # Ya jo version tum use kar rahe ho
    container_name: lavalink
    ports:
      - "2333:2333"
    volumes:
      - ./application.yml:/opt/Lavalink/application.yml # Lavalink ki config file
